Repository FIS2425/patient-svc, pull requests merged in 2025-01, with the labels that each got.

#39 Feature/kubernetes
  .env.example
  .gitignore
  Dockerfile
  docker-compose.yml
  kubernetes/mongo-patient-persistentvolumeclaim.yaml
  kubernetes/mongodb-deployment.yaml
  kubernetes/mongodb-service.yaml
  kubernetes/patient-deployment.yaml
  kubernetes/patient-service.yaml
  openapi.md
  openapi.yaml
  populators/PatientPopulator.js
  src/config/index.js
  src/config/logger.js
  src/controllers/patientController.js
  src/middleware/verifyAdmin.js
  src/middleware/verifyAuth.js
  src/routes/patientRoute.js
  src/schemas/Patient.js
  tests/integration/controllers/patientController.test.js
Labels: 🐳 Dockerize, ⚙️ Configuration, 🧪 Tests, 🐳 Build

#41 feat: mejorar registro de paciente con creación de usuario y manejo d…
  src/controllers/patientController.js
  src/middleware/verifyAdmin.js
  src/middleware/verifyAuth.js
Labels: size/s

#42 feat: Add KafkaTransport for logging with Kafka
  src/utils/kafkaTransport.js
Labels: size/xs

#43 v1.1.0
  .env.example
  .github/workflows/docker-deploy.yml
  .gitignore
  docker-compose.yml
  kubernetes/mongo-patient-persistentvolumeclaim.yaml
  kubernetes/mongodb-deployment.yaml
  kubernetes/mongodb-service.yaml
  kubernetes/patient-deployment.yaml
  kubernetes/patient-service.yaml
  openapi.md
  openapi.yaml
  package-lock.json
  package.json
  populators/Patient.js
  populators/PatientPopulator.js
  populators/runPopulator.js
  src/config/index.js
  src/config/logger.js
  src/controllers/patientController.js
  src/middleware/verifyAdmin.js
  src/middleware/verifyAuth.js
  src/routes/patientRoute.js
  src/schemas/Patient.js
  src/utils/kafkaTransport.js
  tests/integration/controllers/patientController.test.js
Labels: 📦 Dependencies, 😖 size/l, ⚙️ Configuration, 🧪 Tests, 🚀 CI/CD, 🐳 Build

#44 fix: remove clinicHistoryId from sample patient data
  populators/Patient.js
Labels: size/xs

#45 v1.2.3
  populators/Patient.js
Labels: size/s

#46 Fix/tests
  src/controllers/patientController.js
  tests/integration/controllers/dummy
  tests/integration/controllers/patientController.test.js
  tests/integration/schemas/Patients.test.js
  tests/setup/setup.js
Labels: 😎 size/m, 🧪 Tests

#48 Fix populators error and tests
  populators/Patient.js
  src/controllers/patientController.js
  tests/integration/controllers/dummy
  tests/integration/schemas/Patients.test.js
  tests/setup/setup.js
  tests/unit/controllers/patientController.test.js
Labels: 😎 size/m, 🧪 Tests

#49 fix: update authorization logic to include clinicadmin role and adjus…
  src/controllers/patientController.js
  src/middleware/verifyAdmin.js
  src/middleware/verifyAuth.js
  src/routes/patientRoute.js
Labels: size/xs

#55 feat: add circuit breaker for user and clinic history creation
  package.json
  src/controllers/patientController.js
Labels: 📦 Dependencies, 😎 size/m

#56 v.1.2.0
  .github/workflows/trigger-api-sync.yml
  package.json
  src/controllers/patientController.js
Labels: 📦 Dependencies, 😎 size/m, 🚀 CI/CD

#59 v1.2.1
  src/controllers/patientController.js
Labels: size/s

#60 v1.2.2
  src/controllers/patientController.js
Labels: 😎 size/m
